name: dataselector
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.11
  - pandas=2
  - numpy
  - scipy
  - scikit-learn
  - umap-learn
  - apricot-select
  - optuna
  - matplotlib
  - seaborn
  - pyyaml
  - tqdm
  # Geospatial stack (install from conda-forge)
  - geopandas
  - pyproj
  - shapely
  - fiona
  - rtree
  - pip
  - pip:
    - -r requirements-cpu.txt
